'use strict';

require('dotenv').config();
const mongoose = require('mongoose');
const Exercise = require('../src/models/Exercise');

const EXERCISES = [
  // CHEST (10 exercises)
  {
    name: 'Barbell Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders', 'arms'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Lie flat on the bench with feet planted on the floor. Grip the barbell slightly wider than shoulder-width. Lower the bar to your mid-chest, then press it back up explosively. Keep your back slightly arched and avoid bouncing the bar off your chest.',
    tips: ['Keep your elbows at a 45-degree angle', 'Lower the bar in a controlled manner', 'Press your feet into the floor for stability'],
    isActive: true,
  },
  {
    name: 'Dumbbell Flyes',
    muscleGroup: 'chest',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Lie flat on a bench holding dumbbells above your chest with a slight bend in your elbows. Lower the dumbbells in an arc motion until you feel a stretch in your chest. Return to starting position by squeezing your chest muscles.',
    tips: ['Keep a slight bend in your elbows throughout', 'Feel the stretch at the bottom of the movement', 'Focus on chest contraction at the top'],
    isActive: true,
  },
  {
    name: 'Push-ups',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders', 'arms'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: 'Start in a plank position with hands slightly wider than shoulder-width. Lower your body until your chest nearly touches the floor. Push yourself back up to the starting position.',
    tips: ['Keep your body in a straight line', 'Lower yourself until elbows are at 90 degrees', 'Engage your core throughout'],
    isActive: true,
  },
  {
    name: 'Cable Chest Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficulty: 'intermediate',
    instructions: 'Set up cables at chest height. Grab the handles and step forward to create tension. Press the handles forward, bringing them together at the end of the movement. Return to starting position with control.',
    tips: ['Maintain a slight forward lean', 'Keep constant tension on the cables', 'Squeeze your chest at full extension'],
    isActive: true,
  },
  {
    name: 'Machine Chest Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit on the machine with your back firmly against the pad. Adjust the handles to align with your mid-chest. Press the handles forward until your arms are nearly fully extended. Return slowly to the starting position.',
    tips: ['Keep your head and back against the pad', 'Use a controlled tempo', 'Full range of motion for maximum benefit'],
    isActive: true,
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Sit on an incline bench (30-45 degrees) holding dumbbells at shoulder height. Press the dumbbells upward and slightly inward. Lower them back to the starting position with control.',
    tips: ['Angle targets upper chest', 'Press at a slight angle, not straight up', 'Keep dumbbells aligned above your shoulders'],
    isActive: true,
  },
  {
    name: 'Decline Push-ups',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    instructions: 'Place your feet on an elevated surface and hands on the floor in a plank position. Lower your body until your chest nearly touches the floor. Push back up to the starting position.',
    tips: ['Higher elevation = more difficulty', 'Keep body in straight line', 'Excellent for upper chest development'],
    isActive: true,
  },
  {
    name: 'Barbell Incline Bench Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Set the bench to an incline (30-45 degrees). Lie back with the barbell at chest height. Press the barbell upward and slightly forward. Lower it back to your upper chest.',
    tips: ['Targets upper chest effectively', 'Use slightly lighter weight than flat bench', 'Maintain arch in your upper back'],
    isActive: true,
  },
  {
    name: 'Pec Deck Machine',
    muscleGroup: 'chest',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit on the machine with your back firmly against the pad. Grip the handles and press them together in front of you. Squeeze your chest at the peak of the contraction. Return to starting position with control.',
    tips: ['Excellent isolation exercise', 'Focus on the mind-muscle connection', 'Don\'t let handles go too far back'],
    isActive: true,
  },
  {
    name: 'Resistance Band Chest Press',
    muscleGroup: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Attach resistance bands to a fixed point at chest height. Hold the ends and step forward to create tension. Press forward until arms are extended. Return with control.',
    tips: ['Great for warm-ups', 'Can increase resistance with multiple bands', 'Smooth, controlled tempo'],
    isActive: true,
  },

  // BACK (10 exercises)
  {
    name: 'Barbell Rows',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Bend at your hips and knees, holding a barbell with hands slightly wider than shoulder-width. Keep your chest up and pull the barbell to your lower ribs. Extend your arms and repeat.',
    tips: ['Keep your back straight throughout', 'Pull elbows back and down', 'Maintain tension in your back'],
    isActive: true,
  },
  {
    name: 'Pull-ups',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    instructions: 'Hang from a pull-up bar with hands slightly wider than shoulder-width. Pull your body upward until your chest nearly touches the bar. Lower yourself with control.',
    tips: ['Excellent compound exercise', 'Can use assistance if needed', 'Full range of motion is key'],
    isActive: true,
  },
  {
    name: 'Lat Pulldowns',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Sit at a lat pulldown machine and grab the wide handle. Pull the handle down to your upper chest by engaging your lats. Return to starting position with control.',
    tips: ['Great for beginners', 'Pull elbows down and back', 'Lean back slightly for better rom'],
    isActive: true,
  },
  {
    name: 'Seated Cable Rows',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'cable',
    difficulty: 'intermediate',
    instructions: 'Sit at a cable rowing machine with feet planted on the platform. Pull the handle toward your torso, keeping your back straight. Extend your arms and repeat.',
    tips: ['Keep chest up', 'Squeeze shoulder blades together', 'Controlled movement tempo'],
    isActive: true,
  },
  {
    name: 'Dumbbell Rows',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Place one knee on a bench. Hold a dumbbell in the opposite hand. Row the dumbbell up to your ribcage. Lower and repeat for all reps before switching sides.',
    tips: ['Alternate sides for balanced development', 'Keep hips level', 'Row dumbbell to hip, not chest'],
    isActive: true,
  },
  {
    name: 'Assisted Pull-ups',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Use an assisted pull-up machine set to an appropriate weight. Grip the handles and press the foot platform. Pull yourself upward until your chest nears the handles.',
    tips: ['Great progression to full pull-ups', 'Gradually decrease assistance', 'Full range of motion important'],
    isActive: true,
  },
  {
    name: 'Face Pulls',
    muscleGroup: 'back',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Set a cable machine to head height. Grab a rope attachment with hands facing each other. Pull the rope toward your face, separating the ends. Control the return.',
    tips: ['Excellent shoulder health exercise', 'High reps work well', 'Separate hands at top for best contraction'],
    isActive: true,
  },
  {
    name: 'Machine Row',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at a row machine with feet on platform. Grip the handles and pull them toward your torso. Keep your back against the pad. Return with control.',
    tips: ['Good for isolation', 'Stable starting position', 'Consistent form easier to maintain'],
    isActive: true,
  },
  {
    name: 'Resistance Band Pull Aparts',
    muscleGroup: 'back',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Hold a resistance band in front of you at chest height. Pull the band apart by moving your hands outward. Squeeze your shoulder blades together at the peak.',
    tips: ['Great warm-up exercise', 'Can do for high reps', 'Slow and controlled'],
    isActive: true,
  },
  {
    name: 'Underhand Lat Pulldowns',
    muscleGroup: 'back',
    secondaryMuscles: ['arms'],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Sit at a lat pulldown machine and grab the handle with an underhand grip (palms facing you). Pull down to your upper chest, engaging your lats.',
    tips: ['Underhand grip emphasizes biceps', 'Great variation for lat development', 'Control the eccentric portion'],
    isActive: true,
  },

  // SHOULDERS (10 exercises)
  {
    name: 'Military Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['arms', 'chest'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Stand holding a barbell at shoulder height. Press the barbell upward until arms are fully extended. Lower back to shoulder height with control.',
    tips: ['Brace your core', 'Press in a straight line', 'Keep elbows slightly in front of body'],
    isActive: true,
  },
  {
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['chest', 'arms'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    instructions: 'Hold dumbbells at shoulder height with palms facing forward. Press upward until arms are extended. Lower back to shoulder height.',
    tips: ['Greater range of motion than barbell', 'Dumbbells press slightly inward', 'Can do sitting or standing'],
    isActive: true,
  },
  {
    name: 'Lateral Raises',
    muscleGroup: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Stand holding light dumbbells at your sides. Raise the dumbbells out to the sides until arms are parallel to the ground. Lower with control.',
    tips: ['Slight elbow bend', 'Raise dumbbells in a controlled manner', 'Don\'t swing the weight'],
    isActive: true,
  },
  {
    name: 'Cable Lateral Raises',
    muscleGroup: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Stand with a cable to your side. Grab the handle and raise your arm out to the side until parallel to the ground. Lower with control.',
    tips: ['Constant tension from cable', 'Isolates the shoulder', 'Can do both sides at once'],
    isActive: true,
  },
  {
    name: 'Reverse Pec Deck',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at the reverse pec deck machine facing inward. Grab the handles and pull them outward in an arc motion. Squeeze your rear shoulders at the peak.',
    tips: ['Targets rear deltoids', 'Good isolation exercise', 'Keep chest against pad'],
    isActive: true,
  },
  {
    name: 'Machine Shoulder Press',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['chest', 'arms'],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at a shoulder press machine with back against pad. Grip the handles at shoulder height. Press upward until arms are extended.',
    tips: ['Stable form', 'Good for beginners', 'Consistent range of motion'],
    isActive: true,
  },
  {
    name: 'Upright Rows',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['arms', 'back'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Hold a barbell with a narrow grip in front of your thighs. Pull the barbell upward toward your chin, elbows flaring out. Lower to starting position.',
    tips: ['Elbows higher than hands', 'Good for trap development', 'Can use cables or dumbbells'],
    isActive: true,
  },
  {
    name: 'Shrugs',
    muscleGroup: 'shoulders',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficulty: 'beginner',
    instructions: 'Hold a barbell in front of your thighs with a neutral grip. Shrug your shoulders upward toward your ears. Lower back down in a controlled manner.',
    tips: ['Full range of motion', 'Can pause at top', 'Good for traps'],
    isActive: true,
  },
  {
    name: 'Dumbbell Shrugs',
    muscleGroup: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold dumbbells at your sides. Shrug shoulders upward. Lower back down with control.',
    tips: ['Greater range of motion', 'Can go heavier', 'Better shoulder positioning'],
    isActive: true,
  },
  {
    name: 'Front Raises',
    muscleGroup: 'shoulders',
    secondaryMuscles: ['chest'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Stand holding dumbbells at your sides with palms facing back. Raise dumbbells forward to shoulder height. Lower with control.',
    tips: ['Slight elbow bend', 'Controlled movement', 'Targets front deltoids'],
    isActive: true,
  },

  // ARMS (10 exercises)
  {
    name: 'Barbell Curls',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'barbell',
    difficulty: 'beginner',
    instructions: 'Stand holding a barbell with hands shoulder-width apart, palms facing forward. Curl the barbell upward, keeping elbows stationary. Lower with control.',
    tips: ['Keep elbows at your sides', 'Avoid swinging', 'Full range of motion'],
    isActive: true,
  },
  {
    name: 'Dumbbell Curls',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Stand holding dumbbells at your sides, palms facing forward. Curl dumbbells upward, supinating your wrists. Lower with control.',
    tips: ['Can alternate or do simultaneously', 'Greater range of motion', 'Supinate on the way up'],
    isActive: true,
  },
  {
    name: 'Cable Curls',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Stand facing a cable machine with the handle at waist height. Curl the handle upward, maintaining constant tension. Lower to starting position.',
    tips: ['Constant tension throughout', 'Great for hypertrophy', 'Prevents momentum'],
    isActive: true,
  },
  {
    name: 'Tricep Dips',
    muscleGroup: 'arms',
    secondaryMuscles: ['chest'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: 'Place hands on a bench behind you with legs extended. Lower your body by bending elbows until they reach 90 degrees. Push back up to starting position.',
    tips: ['Can do on dip bars', 'Can add weight for difficulty', 'Full range of motion key'],
    isActive: true,
  },
  {
    name: 'Tricep Rope Pushdowns',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Stand at a cable machine with rope attachment at head height. Push the rope downward by extending your arms, separating the ends. Return with control.',
    tips: ['Keep elbows stationary', 'Separate rope at bottom', 'High reps work well'],
    isActive: true,
  },
  {
    name: 'Hammer Curls',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Stand holding dumbbells with neutral grip (palms facing each other). Curl dumbbells upward. Lower with control.',
    tips: ['Emphasizes brachialis', 'Can hold dumbbells vertical', 'Different angle than standard curls'],
    isActive: true,
  },
  {
    name: 'Machine Tricep Dips',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at a machine dip station. Grip the handles and push downward until arms are extended. Return with control.',
    tips: ['Great for beginners', 'Stable movement', 'Good isolation'],
    isActive: true,
  },
  {
    name: 'Close Grip Bench Press',
    muscleGroup: 'arms',
    secondaryMuscles: ['chest'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Lie on a bench and grip a barbell with hands closer than shoulder-width. Lower the barbell to your chest. Press upward.',
    tips: ['Closer grip = more triceps', 'Keep elbows at 45 degrees', 'Good compound movement'],
    isActive: true,
  },
  {
    name: 'Machine Bicep Curl',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at a bicep machine with back against pad. Curl the handles upward. Lower with control.',
    tips: ['Good isolation', 'Consistent form', 'Beginner-friendly'],
    isActive: true,
  },
  {
    name: 'Overhead Tricep Extension',
    muscleGroup: 'arms',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold a dumbbell behind your head with both hands. Extend your arms upward. Lower back down with control.',
    tips: ['Keep elbows stationary', 'Full range of motion', 'Good isolation'],
    isActive: true,
  },

  // LEGS (10 exercises)
  {
    name: 'Barbell Squats',
    muscleGroup: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    instructions: 'Place barbell on your shoulders. Stand with feet shoulder-width apart. Descend by bending hips and knees until thighs are parallel to the ground. Drive through heels to return.',
    tips: ['Keep chest up', 'Knees over toes', 'Full range of motion'],
    isActive: true,
  },
  {
    name: 'Leg Press',
    muscleGroup: 'legs',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit in a leg press machine with back and head against pad. Place feet on platform shoulder-width apart. Push platform away by extending legs. Return with control.',
    tips: ['Great for beginners', 'No balance required', 'Full range of motion'],
    isActive: true,
  },
  {
    name: 'Leg Curls',
    muscleGroup: 'legs',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Lie face down on a leg curl machine with ankles under the pad. Curl your legs upward toward your glutes. Lower with control.',
    tips: ['Isolates hamstrings', 'Good for balance', 'High reps work well'],
    isActive: true,
  },
  {
    name: 'Leg Extensions',
    muscleGroup: 'legs',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at a leg extension machine with shins under the pad. Extend your legs upward until fully straight. Lower with control.',
    tips: ['Isolates quads', 'Full range of motion', 'Controlled tempo'],
    isActive: true,
  },
  {
    name: 'Walking Lunges',
    muscleGroup: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: 'Stand upright and take a large step forward. Lower your body until front knee is at 90 degrees and rear knee nearly touches ground. Drive forward to next rep.',
    tips: ['Keep torso upright', 'Front knee over ankle', 'Can hold dumbbells'],
    isActive: true,
  },
  {
    name: 'Dumbbell Squats',
    muscleGroup: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    instructions: 'Hold dumbbells at your sides. Stand with feet shoulder-width apart. Squat down until thighs are parallel to ground. Drive through heels to return.',
    tips: ['Dumbbells assist with balance', 'Good for beginners', 'Can do goblet squat hold'],
    isActive: true,
  },
  {
    name: 'Calf Raises',
    muscleGroup: 'legs',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: 'Stand with feet hip-width apart. Rise up onto your toes, lifting your heels off the ground. Lower back down with control.',
    tips: ['Full range of motion', 'Can hold dumbbells', 'High reps effective'],
    isActive: true,
  },
  {
    name: 'Leg Press Calf Raises',
    muscleGroup: 'legs',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at a leg press machine. With legs extended, press the platform using only your calves. Lower with control.',
    tips: ['Full range of motion', 'Machine provides support', 'Easier for beginners'],
    isActive: true,
  },
  {
    name: 'Bulgarian Split Squats',
    muscleGroup: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: 'Place one foot behind you on a bench. Step forward with other leg and lower until back knee nearly touches ground. Drive forward leg back to starting position.',
    tips: ['Unilateral movement', 'Can use dumbbells', 'Great for balance and stability'],
    isActive: true,
  },
  {
    name: 'Smith Machine Squats',
    muscleGroup: 'legs',
    secondaryMuscles: ['core'],
    equipment: 'barbell',
    difficulty: 'beginner',
    instructions: 'Position yourself under the Smith machine bar. Place the bar on your shoulders. Squat down until thighs are parallel. Drive back up.',
    tips: ['Good for beginners', 'Fixed path of movement', 'Safe alternative to free weight squats'],
    isActive: true,
  },

  // CORE (10 exercises)
  {
    name: 'Planks',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: 'Position yourself in a plank position with forearms on ground and toes on floor. Keep body in straight line. Hold for time.',
    tips: ['Engage your core', 'Don\'t let hips sag', 'Can increase difficulty with variations'],
    isActive: true,
  },
  {
    name: 'Cable Crunches',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    instructions: 'Kneel at a cable machine with rope attachment. Hold the rope at chest height. Crunch downward by flexing your abs. Return with control.',
    tips: ['Keep resistance constant', 'Full range of motion', 'Slow tempo for better feel'],
    isActive: true,
  },
  {
    name: 'Hanging Leg Raises',
    muscleGroup: 'core',
    secondaryMuscles: ['arms'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    instructions: 'Hang from a pull-up bar with arms extended. Raise your legs up until parallel to ground. Lower with control.',
    tips: ['Great for lower abs', 'Full range of motion', 'Can use resistance band or weight'],
    isActive: true,
  },
  {
    name: 'Machine Ab Crunches',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'machine',
    difficulty: 'beginner',
    instructions: 'Sit at an ab crunch machine with chest against pad. Push against the pad with your abs. Return with control.',
    tips: ['Good for isolation', 'Beginner-friendly', 'Consistent form'],
    isActive: true,
  },
  {
    name: 'Decline Sit-ups',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    instructions: 'Lie on a decline bench with feet secured. Sit upward by engaging your core. Lower back down with control.',
    tips: ['Hands behind head or across chest', 'Full range of motion', 'Increased difficulty on decline'],
    isActive: true,
  },
  {
    name: 'Ab Wheel Rollouts',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    instructions: 'Kneel with ab wheel in front of you. Roll forward by extending your body. Use your abs to pull yourself back. Return to starting position.',
    tips: ['Advanced exercise', 'Can do from knees or standing', 'Full range of motion key'],
    isActive: true,
  },
  {
    name: 'Bicycle Crunches',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: 'Lie on your back with hands behind head. Bring opposite elbow to opposite knee in a cycling motion. Alternate sides.',
    tips: ['Alternating sides important', 'Control the movement', 'No jerking motions'],
    isActive: true,
  },
  {
    name: 'Dead Bug',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: 'Lie on your back with arms extended toward ceiling and legs at 90 degrees. Lower opposite arm and leg while keeping lower back on ground. Return and alternate.',
    tips: ['Maintain lower back on floor', 'Control tempo', 'Great for stability'],
    isActive: true,
  },
  {
    name: 'Russian Twists',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    instructions: 'Sit with knees bent and feet on floor. Lean back slightly and rotate torso from side to side. Can hold a weight for more difficulty.',
    tips: ['Control the rotation', 'Keep chest up', 'Can hold medicine ball'],
    isActive: true,
  },
  {
    name: 'Cable Woodchops',
    muscleGroup: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'intermediate',
    instructions: 'Stand at cable machine with cable at shoulder height. Grip handle and rotate diagonally downward across your body. Return with control.',
    tips: ['Rotational movement', 'Keep arms extended', 'Controlled tempo'],
    isActive: true,
  },
];

async function seedExercises() {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      console.error('MONGO_URI not found in .env');
      process.exit(1);
    }

    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    // Check if exercises already exist
    const existingCount = await Exercise.countDocuments();
    if (existingCount > 0) {
      console.log(`Database already has ${existingCount} exercises. Skipping seed.`);
      await mongoose.disconnect();
      process.exit(0);
    }

    // Insert exercises
    const result = await Exercise.insertMany(EXERCISES);
    console.log(`✅ Successfully seeded ${result.length} exercises`);

    // Verify distribution
    const distribution = await Exercise.aggregate([
      {
        $group: {
          _id: '$muscleGroup',
          count: { $sum: 1 },
        },
      },
    ]);

    console.log('\nExercise distribution by muscle group:');
    distribution.forEach((d) => {
      console.log(`  ${d._id}: ${d.count} exercises`);
    });

    await mongoose.disconnect();
    console.log('\nDisconnected from MongoDB');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding exercises:', error.message);
    process.exit(1);
  }
}

seedExercises();
